name: CommandsPractice2
version: '${project.version}'
main: me.lionelv.commandspractice2.CommandsPractice2
api-version: '1.20'
commands:
  god:
    description: Become invincible
    usage: /<command>