name: CommandsPractice2
version: '1.0-SNAPSHOT'
main: me.lionelv.commandspractice2.CommandsPractice2
api-version: '1.20'
commands:
  god:
    description: Become invincible
    usage: /<command>
    aliases:
      - lionelmode
      - pro
  feed:
    description: Feed yourself
    usage: /<command>
  fart:
    description: Fart on yourself or something
    usage: /fart <player>
  repeat:
    description: Repeat something
    usage: /<command> <args>
  fly:
    description: Toggle fly
    usage: /<command> <args>
permissions:
  lv.command.god:
    description: permission to run /god
    default: op
  lv.command.feed:
    description: permission to run /feed
    default: op
    children:
      permissions.explode: true #if feed then you get explode
      permissions.kill: false  #if feed you don't get kill
  lv.command.fart:
    description: permission to run /fart
    default: op
  lv.command.fly:
    description: permission to run /fly
    default: op
